FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Dependências de Sistema
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Cópia Estruturada
COPY glpi-ai-system /app/glpi-ai-system
WORKDIR /app/glpi-ai-system

# Instalação de Deps
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir sentence-transformers torch numpy schedule

# Variáveis de Ambiente
ENV PYTHONPATH=/app/glpi-ai-system

CMD ["python", "daemon_classifier.py"]
