from typing import List, Optional
from pydantic import BaseModel, Field

# --- GLPI Entities ---
class GLPICategory(BaseModel):
    id: int
    name: str
    completename: str
    comment: Optional[str] = None
    embedding: Optional[List[float]] = None  # To store vector

# --- API Request/Response ---
class ClassificationRequest(BaseModel):
    description: str = Field(..., description="User issue description")
    title: Optional[str] = Field(None, description="Ticket title")
    max_candidates: int = Field(5, description="Number of candidates to retrieve")

class CategoryScore(BaseModel):
    category_id: int
    name: str
    score: float
    description: Optional[str] = None

class ClassificationResponse(BaseModel):
    selected_category_id: int
    selected_category_name: str
    confidence: float
    reasoning: str
    ticket_type: int = Field(1, description="1=Incident, 2=Request")
    urgency: int = Field(3, description="1-5 (Very Low to Very High)")
    impact: int = Field(3, description="1-5 (Low to High)")
    suggested_title: Optional[str] = Field(None, description="Standardized ticket title generated by AI")
    candidates: List[CategoryScore]

# --- Chat Models ---
class ChatMessage(BaseModel):
    role: str
    content: str
