import { Ticket, TicketStatus } from './types';

// Mock Data simulating GLPI SIS Tickets
export const MOCK_TICKETS: Ticket[] = [
  {
    id: 5181,
    name: "Ar Condicionado - Instalação de aparelho de ar portátil no quarto rosa na Ala Residencial",
    content: "Dados do Formulário 1) Localização : Locais > Palacio Piratini -Ala Residencial 2) Telefone de Contato : 51999206211 3)Serviços Solicitados : Manutenção > Ar Condicionado > Instalação Descrição: Solicita-se técnico de climatização para instalar um aparelho de ar portátil HOJE A TARDE COM URGÊNCIA no quarto rosa de hospedes ao lado da academia.",
    date_creation: "2025-12-05T14:32:00",
    date_mod: null,
    status: TicketStatus.NEW,
    entity: { id: 1, name: "Departamento de Conservação" },
    category: { id: 10, name: "Ar Condicionado" },
    requester: { id: 101, name: "Lauro Junior", username: "lauro-junior" },
    technician: null,
    group: null,
  },
  {
    id: 5180,
    name: "GRADIS",
    content: "Solicito manutenção nos gradis do jardim frontal, apresentam pontos de ferrugem avançada próximos ao portão principal.",
    date_creation: "2025-12-05T14:07:00",
    date_mod: "2025-12-05T15:00:00",
    status: TicketStatus.PROCESSING,
    entity: { id: 2, name: "Divisão de Conservação" },
    category: { id: 12, name: "Serralheria" },
    requester: { id: 102, name: "João Severiano", username: "joao-severiano" },
    technician: { id: 102, name: "João Severiano", username: "joao-severiano" },
    group: { id: 5, name: "Manutenção Predial" },
  },
  {
    id: 5179,
    name: "Elétrica - Troca de lâmpadas no Salão Negrinho do Pastoreio",
    content: "Diversas lâmpadas queimadas no lustre central. Necessário andaime para acesso.",
    date_creation: "2025-12-04T09:15:00",
    date_mod: null,
    status: TicketStatus.PLANNED,
    entity: { id: 1, name: "Departamento de Conservação" },
    category: { id: 11, name: "Elétrica" },
    requester: { id: 103, name: "Maria Clara", username: "maria-clara" },
    technician: { id: 104, name: "Carlos Eletricista", username: "carlos-eletro" },
    group: null,
  },
  {
    id: 5175,
    name: "Hidráulica - Vazamento no banheiro feminino do 2º andar",
    content: "Relato de vazamento constante na pia do banheiro. Aparentemente problema no sifão.",
    date_creation: "2025-12-03T11:20:00",
    date_mod: "2025-12-04T10:00:00",
    status: TicketStatus.PENDING,
    entity: { id: 1, name: "Departamento de Conservação" },
    category: { id: 13, name: "Hidráulica" },
    requester: { id: 105, name: "Ana Paula", username: "ana-paula" },
    technician: { id: 106, name: "Mario Encanador", username: "mario-encanador" },
    group: null,
  },
  {
    id: 5113,
    name: "Marcenaria - Conserto de porta emperrada",
    content: "Porta do gabinete de crise não está fechando corretamente. Necessita ajuste nas dobradiças.",
    date_creation: "2025-11-28T08:00:00",
    date_mod: "2025-11-30T16:00:00",
    status: TicketStatus.SOLVED,
    entity: { id: 1, name: "Departamento de Conservação" },
    category: { id: 14, name: "Marcenaria" },
    requester: { id: 101, name: "Lauro Junior", username: "lauro-junior" },
    technician: { id: 107, name: "José Marceneiro", username: "jose-marceneiro" },
    group: null,
  },
  {
    id: 5100,
    name: "Jardinagem - Poda de árvores pátio interno",
    content: "Solicitação de poda preventiva das árvores que estão encostando na fiação elétrica.",
    date_creation: "2025-11-20T10:00:00",
    date_mod: "2025-11-21T14:00:00",
    status: TicketStatus.CLOSED,
    entity: { id: 2, name: "Divisão de Conservação" },
    category: { id: 15, name: "Jardinagem" },
    requester: { id: 108, name: "Roberto Silva", username: "roberto-silva" },
    technician: null,
    group: { id: 5, name: "Manutenção Externa" },
  }
];