version: '3.8'

services:
  # --- WhatsApp HTTP API (WAHA) ---
  waha:
    image: devlikeapro/waha:latest
    container_name: waha_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_DASHBOARD_ENABLED=true
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=admin
      - WHATSAPP_RESTART_ON_FAIL=true
      - WAHA_API_KEY=mysecretkey
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - waha_data:/app/sessions

  # --- Agent Service ---
  glpi-agent:
    build: .
    image: glpi-agent:latest
    container_name: glpi_classifier_service
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - ENVIRONMENT=test
      - AGENT_DEVICE=cuda
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - LLM_API_KEY=${LLM_API_KEY}
      - SANDBOX=false
      # WAHA Configuration
      - WAHA_BASE_URL=http://waha:3000
      - WAHA_API_KEY=mysecretkey

    volumes:
      - ./:/app
      - ./model_cache:/root/.cache/torch/sentence_transformers

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    depends_on:
      - waha

volumes:
  waha_data:
