services:
  vllm-llm-awq:
    image: vllm/vllm-openai:latest
    container_name: glpi-vllm-awq
    runtime: nvidia
    shm_size: "16g"
    environment:
      - HF_TOKEN=${HF_TOKEN:-} # Opcional, modelo é público
      - TZ=${TZ}
      - VLLM_USE_TRITON_FLASH_ATTN=0
    volumes:
      - C:\AI_DATA\cache\huggingface:/root/.cache/huggingface
    ports:
      - "9000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped
    command: >
      --model Qwen/Qwen2.5-Coder-7B-Instruct-AWQ --quantization awq --gpu-memory-utilization 0.50 --max-model-len 8192 --dtype auto --trust-remote-code --enforce-eager --disable-custom-all-reduce --disable-log-stats
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      start_period: 300s
      interval: 30s
      timeout: 10s
      retries: 60
    stop_grace_period: 2m
