services:
  vllm-llm-awq:
    image: vllm/vllm-openai:latest
    container_name: glpi-vllm-awq
    runtime: nvidia
    shm_size: "16g"
    environment:
      - HF_TOKEN=${HF_TOKEN:-} # Opcional, modelo é público
    volumes:
      - C:\NIM\cache\huggingface:/root/.cache/huggingface
    ports:
      - "9000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped
    command: >
      --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --quantization awq_marlin --gpu-memory-utilization 0.90 --max-model-len 4096 --dtype auto --trust-remote-code --enforce-eager --disable-log-stats
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      start_period: 300s
      interval: 30s
      timeout: 10s
      retries: 60
    stop_grace_period: 2m
